In [1]:
# 텐서 만들기
import torch

# (1) 초기화되지 않은 텐서
a = torch.empty(2, 3)
print("1️⃣ torch.empty(2,3)")
print(a, "\n")

# (2) 0으로 채워진 텐서
b = torch.zeros(2, 3)
print("2️⃣ torch.zeros(2,3)")
print(b, "\n")

# (3) 1로 채워진 텐서
c = torch.ones(2, 3)
print("3️⃣ torch.ones(2,3)")
print(c, "\n")

# (4) 정규분포를 따르는 난수 텐서
d = torch.randn(2, 3)
print("4️⃣ torch.randn(2,3)")
print(d, "\n")

# (5) 직접 값으로 텐서 생성
e = torch.tensor([1, 2, 3])
print("5️⃣ torch.tensor([1,2,3])")
print(e)


1️⃣ torch.empty(2,3)
tensor([[-5.4108e+08,  1.1659e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]) 

2️⃣ torch.zeros(2,3)
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

3️⃣ torch.ones(2,3)
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

4️⃣ torch.randn(2,3)
tensor([[ 0.5713, -0.0389, -0.2104],
        [ 0.3161, -0.3576, -1.0556]]) 

5️⃣ torch.tensor([1,2,3])
tensor([1, 2, 3])


```
출력값이
1️⃣ torch.empty(2,3)
tensor([[-5.4108e+08,  1.1659e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]) 
         이렇게 안에 비어있는게 아니라 임의의 데이터로 채워져있는 이유.
         
torch.empty()는 “초기화하지 않은 텐서”야
torch.empty(2,3)는 말 그대로

“2×3 크기의 텐서를 만들되, 안에 있는 값을 초기화하지 않는다”
는 뜻이야.

🧠 즉, 어떤 일이 일어나냐면
PyTorch가 메모리 공간(=RAM 또는 GPU 메모리)을 확보함.
그런데 그 공간을 0으로 초기화하지 않음.
그 메모리 위치에는 이전에 다른 연산이나 프로그램이 썼던 값이 그대로 남아 있음.
그래서 결과가 이렇게 나오는 거야 👇

tensor([[-5.4108e+08,  1.1659e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


→ 쓰레기 값 (garbage value) 이라고 부르는 임의의 데이터가 들어 있는 거야.
```