In [1]:
import torch
import torch.nn as nn

# 1. 입력 텐서 (1채널, 5x5)
input_tensor = torch.tensor([[[1, 2, 3, 0, 1],
                              [0, 1, 2, 3, 0],
                              [1, 0, 1, 2, 3],
                              [2, 1, 0, 1, 2],
                              [0, 2, 1, 0, 1]]], dtype=torch.float32)  # shape: [1, 5, 5]

# 2. Conv2d 설정: 1 입력 채널, 1 출력 채널, 커널 3x3
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, bias=False)

# 커널 값 직접 지정 (예시: 가장자리 강조하는 필터)
conv.weight.data = torch.tensor([[[[1, 0, -1],
                                   [1, 0, -1],
                                   [1, 0, -1]]]], dtype=torch.float32)

# 3. 합성곱 적용
output = conv(input_tensor.unsqueeze(0))  # 배치 차원 추가, shape: [1, 1, 5, 5] → [1, 1, 3, 3]

print("입력 텐서:")
print(input_tensor)
print("\n커널:")
print(conv.weight.data)
print("\n출력 텐서 (합성곱 결과):")
print(output.squeeze())  # 배치/채널 차원 제거


입력 텐서:
tensor([[[1., 2., 3., 0., 1.],
         [0., 1., 2., 3., 0.],
         [1., 0., 1., 2., 3.],
         [2., 1., 0., 1., 2.],
         [0., 2., 1., 0., 1.]]])

커널:
tensor([[[[ 1.,  0., -1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]]]])

출력 텐서 (합성곱 결과):
tensor([[-4., -2.,  2.],
        [ 0., -4., -2.],
        [ 1.,  0., -4.]], grad_fn=<SqueezeBackward0>)
