In [ ]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조

In [2]:
# 0차원 텐서 : 스칼라 25 - 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태 [1,2,3,4]
# 2차원 텐서(행렬) : 행과 열로 이루어진 데이터 표데이터, 흑백이미지
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R,G,B)
# 고차원 텐서
    # 4차원 텐서 : 동영상 : 이미지개수 X 가로픽셀 X 세로픽셀 X 채널정보

In [3]:
# 기존 컨테이너 자료형이 아닌 텐서를 사용하는 이유 :
# 1 ) 데이터 표준 형식 : 일관된 숫자형식으로 표현
# 2 ) 효율적인 계산 : GPU를 지원한다.^ -> 병렬연산에 유리
                        # 프로그램, 라이브러리, 또는 프레임워크^가 GPU(그래픽 처리 장치)^를 활용할 수 있다는 의미,
                        # 연산을 CPU^ 대신 GPU에서 수행할 수 있다.
                        # GPU를 쓰면 학습 속도가 CPU 대비 수십 배 빠를 수 있다.



# 텐서가 미분으로 자동미분^이 가능하다.
    # ^ 자동미분 :

# 딥러닝 프레임워크 :  파이토치, 텐서플로

In [4]:
%pip install torch torchvision

  Using cached torch-2.9.0-cp313-cp313-win_amd64.whl.metadata (30 kB)
  Using cached torchvision-0.24.0-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.9.0-cp313-cp313-win_amd64.whl (109.3 MB)
Using cached torchvision-0.24.0-cp313-cp313-win_amd64.whl (4.3 MB)
Using cached fsspec-2025.9.0-py3-none-any.whl (199 kB)
Using cached networkx-3.5-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ---------------------------------------- 7.0/7.0 MB 40.1 MB/s  0:00:00
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
 

In [5]:
# 파이토치는 넘파이의 array와 유사하다.

In [6]:
# 기본 연산
import torch

# 빈 텐서 생성
x = torch.empty(3,4) # 3개씩 4개의 컬럼을 가진 빈텐서 생성
x

tensor([[1.0927e-19, 1.7208e-42, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [7]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.0530, 0.8139, 0.7911, 0.0113],
        [0.4916, 0.2188, 0.5209, 0.1772],
        [0.9208, 0.5576, 0.3241, 0.6931]])

In [9]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long) # .zero() : 텐서 내부를 0으로 채운다.
                                 # dtpye = torch.long : torch.long = torch.int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [10]:
# 1초 채워진 텐서
torch.ones(3,4,dtype=torch.long) # .one() : 텐서 내부를 1로 채운다.

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [11]:
import numpy as np
print(torch.tensor([3.5,3,2.1]))
print(np.array([3.5,3,2.1]))

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [12]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x,dtype=torch.float)
x, y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 0.5903,  1.1194,  0.3126, -0.1614],
         [ 1.9836,  0.0440, -1.3670,  1.3985],
         [ 0.2676,  0.2970,  0.5385,  0.4827]]))

In [13]:
# 행렬의 덧셈
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x, y, x+y # 덧셈을 하면, 넘파이처럼 동일한 인덱스의 요소들끼리 매치되어 합쳐진다.^그렇다면 행렬의 형식이 다르면 어떻게 될까?^

(tensor([[0.4126, 0.2238, 0.1342, 0.5716],
         [0.4344, 0.9930, 0.9892, 0.9364],
         [0.8531, 0.6860, 0.0041, 0.5730]]),
 tensor([[0.0801, 0.4946, 0.2691, 0.4347],
         [0.8163, 0.7929, 0.0546, 0.0130],
         [0.7656, 0.3434, 0.8593, 0.0314]]),
 tensor([[0.4927, 0.7183, 0.4033, 1.0063],
         [1.2507, 1.7859, 1.0438, 0.9494],
         [1.6187, 1.0293, 0.8634, 0.6044]]))

In [ ]:
torch.add(x,y)

In [ ]:
# in-place :
    # 이전에 데이터프레임을 수정하고나서, 그 데이터프레임을 다시 기존데이터 프레임에 다시 재정의를 해주는 것을
    # 알아서 해주는 기능과 동일한 기능을 텐서에서 적용하는 방법
# y = y + x    y+=x
y.add_(x)

In [ ]:
y

In [ ]:
# 행렬 곱셈
    # 학습연산중에서 핵심적인 연산이므로 잘알아두기.
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y), x@y # 파이썬 3.5 부터 x@y 로 동일한 기능을 제공한다.

In [ ]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
x*y # ^*이거 안되는거 아니였어?

In [ ]:
# 슬라이싱 가능
    # 파이썬과 사용방식 동일
        # : 의 기능 ^ list(:,3) 이런거 ^
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item())
# 타입이 다르다.
# torch.Tensor / float
# torch.Tensor의 경우에는 GPU에서만 사용가능하다.
# float의 경우에는 CPU에서 사용한다. ^ CPU에서만 사용가능한지? ^

In [ ]:
# 텐서 크기 변경 reshape, view 
    # numpy 동일한 기능 reshape
import torch
x = torch.rand(4,4)
y = x.view(-1) # -1 자동 계산
               # ^ x.view() : PyTorch에서 텐서(tensor)의 형상(shape)이나 차원(dim)을 바꾸는 함수
               # 
x, y, x.shape, y.shape

(tensor([[0.0722, 0.9328, 0.6356, 0.9335],
         [0.1846, 0.2420, 0.6718, 0.6903],
         [0.3382, 0.6948, 0.1393, 0.3037],
         [0.6694, 0.7975, 0.9448, 0.4654]]),
 tensor([0.0722, 0.9328, 0.6356, 0.9335, 0.1846, 0.2420, 0.6718, 0.6903, 0.3382,
         0.6948, 0.1393, 0.3037, 0.6694, 0.7975, 0.9448, 0.4654]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [ ]:
# x, 4 by 4
# view : reshape # 텐서 모양 변경
# size : shape # 텐서 모양 확인
# 가독성.... view size  사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시
x.view(-1,-1), x.size() # RuntimeError: only one dimension can be inferred

RuntimeError: only one dimension can be inferred

In [21]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
# 1 ) np.array(a)
# 2 ) a.numpy()
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
# 넘파이 -> 텐서
import torch
import numpy as np
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [ ]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda') # gpu
    # 텐서들은 gpu에서 연산해되기 때문에 생성을 gpu를 생성
    x = torch.ones(5,device=device) # gpu
    y = torch.ones(5) # cpu
    y = y.to(device) # cpu -> gpu 로 이동
    # 변수하나는 gpu , 또다른 변수 하나는 cpu에 있다면 연산이 안된다.
    z = x+y
    print(f'{x}')
    print(f'{z.to("cpu",torch.double)}')
else:
    print('CUDA를 사용할수 없습니다.')
    device = torch.device("cpu")

In [ ]:
# 내용정리

# 행렬의 곱
# ( x, y ) * ( x1, y1 )
# y, x1의 차수는 같아야 한다...
# 행렬곱의 결과는 x, y1

# 텐서는 딥러닝을 위해 만들 자료구조... 내부에 gpu 연산에 특화된 구조 일반적인 모양은 넘파이와 동일
# 텐서는 gpu 연산을 지원

In [ ]:
# 자동 미분 (Autograd) 매 계산과정마다 해당 계산과정의 미분값을 저장
# 파이토치 required grade = True로 설정하면 계산 그래프라는 형태로 기록 - 동영상 녹화와 비슷 한 원리
# backword() 호출하면 이과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다

In [ ]:
# ^
x = torch.ones(2,2, requires_grad=True)
x,  x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [ ]:
# ^
y = x + 2   # y도 계산 그래프에 추가
print(y, y.grad_fn)
z = y*y*3
out = z.mean()
z, out

In [ ]:
# 기울기.... 구하는 과정을... 역전파 --> 기울기 계산
# 최종결과가 out에서부터 시작해서 계산그래프를 꺼꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분 
out.backward()
x.grad

In [ ]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2

# d-out/dxi = 

# 직접계산과 지원하는 자동미분법으로 나온값을 비교해보기 ^

In [22]:
# 기울기 제어
# 역전파
# reaquired_grad = True연산 추적
import torch
x = torch.randn(3,requires_grad=True)
print(x)
# y는 x 로부터 연산기록을 물려받음
y = x*2

# 노름(유클리드 노름) 벡터의 크기를 측정하는 방법(원점으로 부터 벡터까지의 거리) 모든 요소들가각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제 데이터의 크기를 확인해서 반복
i=0
while  y.data.norm() <1000:
    y = y*2
    i += 1
print(f'y : {y}')
print(f'반복횟수 :{i} y=x*2^i+1')

tensor([ 0.5332,  0.3226, -1.0479], requires_grad=True)
y : tensor([  546.0018,   330.3425, -1072.9999], grad_fn=<MulBackward0>)
반복횟수 :9 y=x*2^i+1


In [ ]:
# 벡터에 대한 역전파 (야코비안 행렬)
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안 - 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float)
    # ^ torch.tensor
y.backward(v) # y를 x에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터 v을 곱하라는 의미
print(f'x.grad : {x.grad}')


x.grad : None


```
스칼라 백워드 Sclaer Backward : 역전파로 구하는 기울기가 하나 일때
out.backward()
최종점수가 숫자하나, ex) 수학공부 1시간 했을때 최종점수에 몇점의 영향을 줬는지
최종 목표가 하나(스칼라)이기 때문에 각 원인 (각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backward : 기울기가 여러개 일때
y.backward(v)
과목별 점수가 담긴 성적표(벡터) : 공부시간이 얼마나 성적에 영향을 줬는지 물어보면 애매함
                                    국어 성적인지 영어 성적인지 과학 성적인지 등등 경우의 수가 구체적으로 안추려짐
가중치 또는 중요도를 알려주는 벡터 v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
                                                 # 영어 국어 수학 순으로 가중치 부여
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
```

In [ ]:
x.requires_grad # .requires_grad :

In [ ]:
# 각 학습을 진행하면서 도중에 모델의 성능을 평가가 필요 - 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부 : {(x**2).requires_grad}')
# .detach() : 계산 그래프에서 텐서를 분리


no_grad 내부 : False


In [ ]:
# 데이터 전처리
    # 결측치 : 제거하거나 대처 (평균, 증위수, 주변데이터를 이용... 다양한 알고리즘)
    # 클래스 불균형 : over / dowmn sampling, SMOTE SMOTEEN
# 데이터 특성 공학 : 연속형 -> 범주형 , 사이클릭 인코딩
    # 범주형 숫자 숫자사이에 연관성이 있으면 이것도 학습
    # 연관성이 전혀없는 범주형 라벨링 - onehot
    # 범주형이지만 순서나 크기가 있는 범주형은 라벨링 그대로 유지

# 머신러닝
# 지도학습
    # 회귀
        # LinearRegrssion
    # 분류
        # SVM
        # Kneighbors
        # Decision Tree
# 비지도 학습
    # 클러스터
        # kmeans
        # dbscan