In [54]:
# Tensor
# 데이터를 저장하는 다차원 배열 또는 컨테이너
# 딥러닝이 학습할때 사용하는 자료구조

In [55]:
# 0차원 텐서 : 스칼라 25 - 단일 데이터
# 1차원 텐서(벡터) : 리스트 형태 [1,2,3,4]
# 2차원 텐서(행렬) : 행과 열로 이루어진 데이터 표데이터, 흑백이미지
# 3차원 텐서 : 컬러이미지 흑백이미지 + 채널정보(R,G,B)
# 고차원 텐서
    # 4차원 텐서 : 동영상 : 이미지개수 X 가로픽셀 X 세로픽셀 X 채널정보

In [56]:
# 기존 컨테이너 자료형이 아닌 텐서를 사용하는 이유 :
# 1 ) 데이터 표준 형식 : 일관된 숫자형식으로 표현
# 2 ) 효율적인 계산 : GPU를 지원한다.^ -> 병렬연산에 유리
                        # 프로그램, 라이브러리, 또는 프레임워크^가 GPU(그래픽 처리 장치)^를 활용할 수 있다는 의미,
                        # 연산을 CPU^ 대신 GPU에서 수행할 수 있다.
                        # GPU를 쓰면 학습 속도가 CPU 대비 수십 배 빠를 수 있다.



# 텐서가 미분으로 자동미분^이 가능하다.
    # ^ 자동미분 :

# 딥러닝 프레임워크 :  파이토치, 텐서플로

In [57]:
%pip install torch torchvision

Note: you may need to restart the kernel to use updated packages.


In [58]:
# 파이토치는 넘파이의 array와 유사하다.

In [59]:
# 기본 연산
import torch

# 빈 텐서 생성
x = torch.empty(3,4) # 3개씩 4개의 컬럼을 가진 빈텐서 생성
x

tensor([[0.7171, 1.0450, 0.7820, 1.7593],
        [1.0673, 1.4703, 0.8388, 1.3618],
        [0.7215, 0.8907, 1.1170, 0.8946]])

In [60]:
# 랜덤 텐서
x = torch.rand(3,4)
x

tensor([[0.2453, 0.5821, 0.0209, 0.2049],
        [0.2285, 0.0994, 0.9454, 0.3831],
        [0.8623, 0.3396, 0.5736, 0.9123]])

In [61]:
# 0으로 텐서 초기화
torch.zeros(3,4,dtype=torch.long) # .zero() : 텐서 내부를 0으로 채운다.
                                 # dtpye = torch.long : torch.long = torch.int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [62]:
# 1초 채워진 텐서
torch.ones(3,4,dtype=torch.long) # .one() : 텐서 내부를 1로 채운다.

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [63]:
import numpy as np
print(torch.tensor([3.5,3,2.1]))
print(np.array([3.5,3,2.1]))

tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [64]:
# 기존의 텐서를 기반으로 새로운 텐서 생성
x = torch.ones(3,4)
y = torch.randn_like(x,dtype=torch.float)
x, y

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 1.3849, -0.5540, -0.3258, -2.5928],
         [ 0.6004,  0.1058, -0.6435,  0.0953],
         [-1.5452, -0.3968, -1.6408, -1.3000]]))

In [65]:
# 행렬의 덧셈
import torch
x = torch.rand(3,4)
y = torch.rand(3,4)
x, y, x+y # 덧셈을 하면, 넘파이처럼 동일한 인덱스의 요소들끼리 매치되어 합쳐진다.^그렇다면 행렬의 형식이 다르면 어떻게 될까?^

(tensor([[0.1547, 0.4221, 0.2999, 0.5995],
         [0.8310, 0.4461, 0.6206, 0.9483],
         [0.9781, 0.0519, 0.8395, 0.8716]]),
 tensor([[0.1195, 0.3248, 0.7927, 0.8217],
         [0.6815, 0.1861, 0.9266, 0.1307],
         [0.3266, 0.6215, 0.6949, 0.0961]]),
 tensor([[0.2742, 0.7469, 1.0926, 1.4212],
         [1.5125, 0.6322, 1.5471, 1.0789],
         [1.3047, 0.6734, 1.5344, 0.9677]]))

In [66]:
torch.add(x,y)

tensor([[0.2742, 0.7469, 1.0926, 1.4212],
        [1.5125, 0.6322, 1.5471, 1.0789],
        [1.3047, 0.6734, 1.5344, 0.9677]])

In [67]:
# in-place :
    # 이전에 데이터프레임을 수정하고나서, 그 데이터프레임을 다시 기존데이터 프레임에 다시 재정의를 해주는 것을
    # 알아서 해주는 기능과 동일한 기능을 텐서에서 적용하는 방법
# y = y + x    y+=x
y.add_(x)

tensor([[0.2742, 0.7469, 1.0926, 1.4212],
        [1.5125, 0.6322, 1.5471, 1.0789],
        [1.3047, 0.6734, 1.5344, 0.9677]])

In [68]:
y

tensor([[0.2742, 0.7469, 1.0926, 1.4212],
        [1.5125, 0.6322, 1.5471, 1.0789],
        [1.3047, 0.6734, 1.5344, 0.9677]])

In [69]:
# 행렬 곱셈
    # 학습연산중에서 핵심적인 연산이므로 잘알아두기.
x = torch.rand(3,4)
y = torch.rand(4,5)
x, y, torch.mm(x,y), x@y # 파이썬 3.5 부터 x@y 로 동일한 기능을 제공한다.

(tensor([[0.1772, 0.4687, 0.0168, 0.2231],
         [0.4428, 0.1080, 0.3786, 0.9387],
         [0.1789, 0.4836, 0.7283, 0.4168]]),
 tensor([[0.1169, 0.3931, 0.0972, 0.4334, 0.5442],
         [0.7490, 0.6330, 0.2943, 0.4504, 0.6041],
         [0.7631, 0.7773, 0.4486, 0.3508, 0.1549],
         [0.7146, 0.6518, 0.1505, 0.8596, 0.2908]]),
 tensor([[0.5441, 0.5248, 0.1963, 0.4856, 0.4471],
         [1.0925, 1.1486, 0.3860, 1.1803, 0.6378],
         [1.2367, 1.2141, 0.5491, 0.9090, 0.6235]]),
 tensor([[0.5441, 0.5248, 0.1963, 0.4856, 0.4471],
         [1.0925, 1.1486, 0.3860, 1.1803, 0.6378],
         [1.2367, 1.2141, 0.5491, 0.9090, 0.6235]]))

In [70]:
x = torch.tensor([1,2,3])
y = torch.tensor([1,2,3])
x*y # ^*이거 안되는거 아니였어?

tensor([1, 4, 9])

In [71]:
# 슬라이싱 가능
    # 파이썬과 사용방식 동일
        # : 의 기능 ^ list(:,3) 이런거 ^
x = torch.rand(4,5)
x[1,1], x[1,1].item(), type(x[1,1]), type(x[1,1].item())
# 타입이 다르다.
# torch.Tensor / float
# torch.Tensor의 경우에는 GPU에서만 사용가능하다.
# float의 경우에는 CPU에서 사용한다. ^ CPU에서만 사용가능한지? ^

(tensor(0.6847), 0.6846614480018616, torch.Tensor, float)

In [72]:
# 텐서 크기 변경 reshape, view 
    # numpy 동일한 기능 reshape
import torch
x = torch.rand(4,4)
y = x.view(-1) # -1 자동 계산
               # ^ x.view() : PyTorch에서 텐서(tensor)의 형상(shape)이나 차원(dim)을 바꾸는 함수
               # 
x, y, x.shape, y.shape

(tensor([[0.9033, 0.1248, 0.7417, 0.4017],
         [0.7258, 0.2462, 0.3490, 0.6460],
         [0.6802, 0.4655, 0.4598, 0.8265],
         [0.2299, 0.7858, 0.3384, 0.8455]]),
 tensor([0.9033, 0.1248, 0.7417, 0.4017, 0.7258, 0.2462, 0.3490, 0.6460, 0.6802,
         0.4655, 0.4598, 0.8265, 0.2299, 0.7858, 0.3384, 0.8455]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [73]:
# x, 4 by 4
# view : reshape # 텐서 모양 변경
# size : shape # 텐서 모양 확인
# 가독성.... view size  사용되었다는 것은 해당 자료구조가 텐서라는 것을 명시
#x.view(-1,-1), x.size() # RuntimeError: only one dimension can be inferred

In [74]:
# 텐서 -> 넘파이
import torch
import numpy as np
a = torch.ones(5)
# 1 ) np.array(a)
# 2 ) a.numpy()
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [75]:
# 넘파이 -> 텐서
import torch
import numpy as np
a = np.array([1,2,3,4,5])
torch.from_numpy(a)

tensor([1, 2, 3, 4, 5])

In [76]:
# GPU 사용
import torch
if torch.cuda.is_available():
    device = torch.device('cuda') # gpu
    # 텐서들은 gpu에서 연산해되기 때문에 생성을 gpu를 생성
    x = torch.ones(5,device=device) # gpu
    y = torch.ones(5) # cpu
    y = y.to(device) # cpu -> gpu 로 이동
    # 변수하나는 gpu , 또다른 변수 하나는 cpu에 있다면 연산이 안된다.
    z = x+y
    print(f'{x}')
    print(f'{z.to("cpu",torch.double)}')
else:
    print('CUDA를 사용할수 없습니다.')
    device = torch.device("cpu")

CUDA를 사용할수 없습니다.


In [77]:
# 내용정리

# 행렬의 곱
# ( x, y ) * ( x1, y1 )
# y, x1의 차수는 같아야 한다...
# 행렬곱의 결과는 x, y1

# 텐서는 딥러닝을 위해 만들 자료구조... 내부에 gpu 연산에 특화된 구조 일반적인 모양은 넘파이와 동일
# 텐서는 gpu 연산을 지원

In [78]:
# 자동 미분 (Autograd) 매 계산과정마다 해당 계산과정의 미분값을 저장
# 파이토치 required grade = True로 설정하면 계산 그래프라는 형태로 기록 - 포토샵 되돌리기 기능
# backword() 호출하면 이과정을 거꾸로 되감으면서 각 단계의 미분값을 계산해 최종 기울기를 얻는다

In [79]:
# ^
x = torch.ones(2,2, requires_grad=True)
x,  x.size()

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [80]:
# ^
y = x + 2   # y도 계산 그래프에 추가
print(y, y.grad_fn)
# tensor([[3., 3.],
#         [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x0000023543BCDAB0>
# grad_fn은 객체 이름을 통해 어떤 연산인지 간접적으로 보여줘요.
# <AddBackward0> → 덧셈(add)
# <MulBackward0> → 곱셈(multiply)
# <PowBackward0> → 거듭제곱(power)
# 즉, <AddBackward0> 자체가 “덧셈으로 만들어진 텐서”라는 표시

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>) <AddBackward0 object at 0x000002355C895F00>


In [ ]:

z = y*y*3
out = z.mean()
z, out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [ ]:
# 기울기.... 구하는 과정을... 역전파 --> 기울기 계산
# 최종결과가 out에서부터 시작해서 계산그래프를 꺼꾸로 거슬러 올라가면서 미분의 연쇄법칙을 사용해서 미분값을 계산
# out을 x에 대해서 미분 
out.backward()
x.grad

In [83]:
# out = 1/4(z1+z2+z3+z4)
# z = 3y^2
# y = x + 2

# d-out/dxi = 

# 직접계산과 지원하는 자동미분법으로 나온값을 비교해보기 ^

In [84]:
# 기울기 제어
# 역전파
# reaquired_grad = True연산 추적
import torch
x = torch.randn(3,requires_grad=True)
print(x)
# y는 x 로부터 연산기록을 물려받음
y = x*2

# 노름(유클리드 노름) 벡터의 크기를 측정하는 방법(원점으로 부터 벡터까지의 거리) 모든 요소들가각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제 데이터의 크기를 확인해서 반복
i=0
while  y.data.norm() <1000:
    y = y*2
    i += 1
print(f'y : {y}')
print(f'반복횟수 :{i} y=x*2^i+1')

tensor([ 0.2075,  1.2174, -0.3016], requires_grad=True)
y : tensor([ 212.4758, 1246.6191, -308.8120], grad_fn=<MulBackward0>)
반복횟수 :9 y=x*2^i+1


In [85]:
# 벡터에 대한 역전파 (야코비안 행렬)
# 벡터를 벡터로 미분하면 결과는 행렬인 야코비안 행렬
# pytorch는 전체 야코비안 행렬을 직접 계산하는 대신 야코비안 - 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor([0.1,1.0,0.001],dtype=torch.float)
    # ^ torch.tensor
y.backward(v) # y를 x에 대해 미분한 야코비안 행렬과 입력으로 제공된 벡터 v을 곱하라는 의미
print(f'x.grad : {x.grad}')


x.grad : tensor([ 102.4000, 1024.0000,    1.0240])


```
스칼라 백워드 Sclaer Backward : 역전파로 구하는 기울기가 하나 일때
out.backward()
최종점수가 숫자하나, ex) 수학공부 1시간 했을때 최종점수에 몇점의 영향을 줬는지
최종 목표가 하나(스칼라)이기 때문에 각 원인 (각 변수)의 기여도를 바로 계산

벡터 백워드 Vector Backward : 기울기가 여러개 일때
y.backward(v)
과목별 점수가 담긴 성적표(벡터) : 공부시간이 얼마나 성적에 영향을 줬는지 물어보면 애매함
                                    국어 성적인지 영어 성적인지 과학 성적인지 등등 경우의 수가 구체적으로 안추려짐
가중치 또는 중요도를 알려주는 벡터 v = torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
                                                 # 영어 국어 수학 순으로 가중치 부여
중요도를 반영해서 최종적으로 공부시간의 기여도를 확인
```

In [86]:
x.requires_grad # .requires_grad :

True

In [ ]:
# 각 학습을 진행하면서 도중에 모델의 성능을 평가가 필요 - 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부 : {(x**2).requires_grad}')
# .detach() : 계산 그래프에서 텐서를 분리

no_grad 내부 : False
